server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos (tu SPA sencilla)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend en la subred privada
    location /api/ {
        proxy_pass http://10.0.2.24:3001;
        # EJEMPLO: proxy_pass http://IP_PRIVADA_EC2_BACKEND:3001;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
